-- ══════════════════════════════════════════════════════════════════════════════
-- SUPABASE MIGRATION v8 — Doctor Schedule & Blocked Days
-- Safe to re-run.
-- Run this in Supabase SQL Editor.
-- ══════════════════════════════════════════════════════════════════════════════

-- ── Table: doctor_schedule ───────────────────────────────────────────────────
-- Stores the fixed weekly working hours for each day of the week.
-- day_of_week: 0=Monday, 1=Tuesday, ..., 6=Sunday

-- Keep this migration self-contained for installations where the shared
-- trigger function from an earlier migration is not present.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = timezone('utc', now());
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS doctor_schedule (
    id              bigint generated by default as identity PRIMARY KEY,
    created_at      timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at      timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    day_of_week     integer     NOT NULL,
    day_name        text        NOT NULL,
    morning_start   time,
    morning_end     time,
    afternoon_start time,
    afternoon_end   time,
    is_active       boolean     NOT NULL DEFAULT true,
    CONSTRAINT doctor_schedule_day_unique UNIQUE (day_of_week),
    CONSTRAINT doctor_schedule_valid_day CHECK (day_of_week >= 0 AND day_of_week <= 6)
);

DROP TRIGGER IF EXISTS set_doctor_schedule_updated_at ON doctor_schedule;
CREATE TRIGGER set_doctor_schedule_updated_at
    BEFORE UPDATE ON doctor_schedule
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Pre-seed with default schedule (Mon–Sat, 9–1 AM + 4–7 PM)
INSERT INTO doctor_schedule (day_of_week, day_name, morning_start, morning_end, afternoon_start, afternoon_end, is_active)
VALUES
    (0, 'Monday',    '09:00', '13:00', '16:00', '19:00', true),
    (1, 'Tuesday',   '09:00', '13:00', '16:00', '19:00', true),
    (2, 'Wednesday', '09:00', '13:00', '16:00', '19:00', true),
    (3, 'Thursday',  '09:00', '13:00', '16:00', '19:00', true),
    (4, 'Friday',    '09:00', '13:00', '16:00', '19:00', true),
    (5, 'Saturday',  '09:00', '13:00', NULL,    NULL,    true),
    (6, 'Sunday',    NULL,    NULL,    NULL,    NULL,    false)
ON CONFLICT (day_of_week) DO NOTHING;

-- ── Table: doctor_blocked_days ────────────────────────────────────────────────
-- Stores specific dates the doctor has blocked (emergency, vacation, leave).

CREATE TABLE IF NOT EXISTS doctor_blocked_days (
    id          bigint generated by default as identity PRIMARY KEY,
    created_at  timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    blocked_date date        NOT NULL,
    reason      text        NOT NULL DEFAULT '',
    blocked_by  text        NOT NULL DEFAULT 'doctor',
    CONSTRAINT doctor_blocked_days_date_unique UNIQUE (blocked_date)
);

CREATE INDEX IF NOT EXISTS idx_doctor_blocked_days_date
    ON doctor_blocked_days (blocked_date);

-- ── RLS Policies ─────────────────────────────────────────────────────────────

ALTER TABLE doctor_schedule ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow doctor_schedule select" ON doctor_schedule;
CREATE POLICY "Allow doctor_schedule select"
    ON doctor_schedule FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow doctor_schedule insert" ON doctor_schedule;
CREATE POLICY "Allow doctor_schedule insert"
    ON doctor_schedule FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow doctor_schedule update" ON doctor_schedule;
CREATE POLICY "Allow doctor_schedule update"
    ON doctor_schedule FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE doctor_blocked_days ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow doctor_blocked_days select" ON doctor_blocked_days;
CREATE POLICY "Allow doctor_blocked_days select"
    ON doctor_blocked_days FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow doctor_blocked_days insert" ON doctor_blocked_days;
CREATE POLICY "Allow doctor_blocked_days insert"
    ON doctor_blocked_days FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow doctor_blocked_days delete" ON doctor_blocked_days;
CREATE POLICY "Allow doctor_blocked_days delete"
    ON doctor_blocked_days FOR DELETE TO anon, authenticated USING (true);

-- ══════════════════════════════════════════════════════════════════════════════
-- DONE. Run this after migration_v7_kb_demo_sources.sql.
-- ══════════════════════════════════════════════════════════════════════════════
