-- ══════════════════════════════════════════════════════════════════════════════
-- SPX AI BASE SETUP — Consolidated Schema
-- ══════════════════════════════════════════════════════════════════════════════

-- ── EXTENSIONS ──────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ── CALL LOGS ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS call_logs (
    id                 bigint generated by default as identity PRIMARY KEY,
    created_at         timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    call_room_id       text,
    phone_number       text,
    caller_name        text,
    duration_seconds   integer,
    transcript         text,
    summary            text,
    recording_url      text,
    sentiment          text,
    estimated_cost_usd numeric(10,5),
    call_date          date,
    call_hour          integer,
    call_day_of_week   text,
    was_booked         boolean DEFAULT false,
    interrupt_count    integer DEFAULT 0,
    audio_codec        text
);

CREATE INDEX IF NOT EXISTS idx_call_logs_phone_number ON call_logs (phone_number);
CREATE INDEX IF NOT EXISTS idx_call_logs_call_room_id ON call_logs (call_room_id);

ALTER TABLE call_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all actions for service role" ON call_logs;
CREATE POLICY "Enable all actions for service role" ON call_logs FOR ALL USING (true) WITH CHECK (true);


-- ── REAL-TIME TRANSCRIPTS ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS call_transcripts (
    id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    call_room_id TEXT NOT NULL,
    phone        TEXT,
    role         TEXT CHECK (role IN ('user', 'assistant')),
    content      TEXT,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_call_transcripts_room  ON call_transcripts (call_room_id);
CREATE INDEX IF NOT EXISTS idx_call_transcripts_phone ON call_transcripts (phone);

ALTER TABLE call_transcripts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon insert transcripts" ON call_transcripts;
CREATE POLICY "Allow anon insert transcripts" ON call_transcripts FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS "Allow anon select transcripts" ON call_transcripts;
CREATE POLICY "Allow anon select transcripts" ON call_transcripts FOR SELECT TO anon USING (true);


-- ── ACTIVE CALLS ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS active_calls (
    room_id      TEXT PRIMARY KEY,
    phone        TEXT,
    caller_name  TEXT,
    status       TEXT DEFAULT 'ringing',
    started_at   TIMESTAMPTZ DEFAULT NOW(),
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE active_calls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon all active_calls" ON active_calls;
CREATE POLICY "Allow anon all active_calls" ON active_calls FOR ALL TO anon USING (true) WITH CHECK (true);


-- ── APPOINTMENTS ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS appointments (
    id              bigint generated by default as identity PRIMARY KEY,
    created_at      timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at      timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    title           text NOT NULL DEFAULT 'Site Visit',
    contact_name    text,
    contact_phone   text,
    scheduled_start timestamptz NOT NULL,
    scheduled_end   timestamptz NOT NULL,
    timezone        text NOT NULL DEFAULT 'Asia/Kolkata',
    status          text NOT NULL DEFAULT 'scheduled',
    notes           text,
    source          text NOT NULL DEFAULT 'manual_ui',
    CONSTRAINT appointments_valid_status CHECK (status IN ('scheduled', 'cancelled', 'completed')),
    CONSTRAINT appointments_valid_source CHECK (source IN ('voice_agent', 'manual_ui')),
    CONSTRAINT appointments_valid_window CHECK (scheduled_end > scheduled_start)
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = timezone('utc', now());
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_appointments_updated_at ON appointments;
CREATE TRIGGER set_appointments_updated_at
BEFORE UPDATE ON appointments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE appointments DROP CONSTRAINT IF EXISTS appointments_no_overlap;
ALTER TABLE appointments ADD CONSTRAINT appointments_no_overlap
    EXCLUDE USING gist (tstzrange(scheduled_start, scheduled_end, '[)') WITH &&)
    WHERE (status = 'scheduled');

CREATE INDEX IF NOT EXISTS idx_appointments_scheduled_start ON appointments (scheduled_start);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments (status);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow internal appointment select" ON appointments;
CREATE POLICY "Allow internal appointment select" ON appointments FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Allow internal appointment insert" ON appointments;
CREATE POLICY "Allow internal appointment insert" ON appointments FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Allow internal appointment update" ON appointments;
CREATE POLICY "Allow internal appointment update" ON appointments FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow internal appointment delete" ON appointments;
CREATE POLICY "Allow internal appointment delete" ON appointments FOR DELETE TO anon, authenticated USING (true);


-- ── AUTOMATION JOBS ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS automation_jobs (
    id                     bigint generated by default as identity PRIMARY KEY,
    created_at             timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    updated_at             timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    channel                text NOT NULL,
    trigger_event          text,
    phone_number           text,
    caller_name            text,
    template_name          text,
    message_type           text DEFAULT 'text' NOT NULL,
    body_text              text DEFAULT '' NOT NULL,
    caption                text DEFAULT '' NOT NULL,
    media_url              text,
    mime_type              text,
    file_name              text,
    asset_id               bigint,
    related_call_room_id   text,
    related_call_log_id    bigint,
    related_appointment_id bigint,
    scheduled_for          timestamptz NOT NULL,
    status                 text DEFAULT 'pending' NOT NULL,
    retry_count            integer DEFAULT 0 NOT NULL,
    max_retries            integer DEFAULT 3 NOT NULL,
    last_error             text,
    idempotency_key        text NOT NULL,
    payload                jsonb DEFAULT '{}'::jsonb NOT NULL,
    provider_message_id    text,
    dispatch_id            text,
    CONSTRAINT automation_jobs_channel_check CHECK (channel IN ('call')),
    CONSTRAINT automation_jobs_status_check CHECK (
        status IN ('pending', 'retry', 'processing', 'sent', 'failed', 'cancelled', 'pending_review', 'launched')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_automation_jobs_idempotency ON automation_jobs (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_automation_jobs_schedule_status ON automation_jobs (status, scheduled_for);

DROP TRIGGER IF EXISTS set_automation_jobs_updated_at ON automation_jobs;
CREATE TRIGGER set_automation_jobs_updated_at
BEFORE UPDATE ON automation_jobs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE automation_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow automation jobs all" ON automation_jobs;
CREATE POLICY "Allow automation jobs all" ON automation_jobs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


-- ── CALL TURN METRICS ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS call_turn_metrics (
    id                 bigint generated by default as identity PRIMARY KEY,
    created_at         timestamptz DEFAULT timezone('utc', now()) NOT NULL,
    call_room_id       text,
    phone_number       text,
    turn_index         integer NOT NULL DEFAULT 0,
    speaker            text NOT NULL DEFAULT 'assistant',
    stt_endpoint_ms    numeric,
    llm_first_token_ms numeric,
    tts_first_audio_ms numeric,
    tool_ms            numeric,
    total_turn_ms      numeric,
    metadata           jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT call_turn_metrics_speaker_check CHECK (speaker IN ('assistant', 'system'))
);

CREATE INDEX IF NOT EXISTS idx_call_turn_metrics_room_turn ON call_turn_metrics (call_room_id, turn_index);

ALTER TABLE call_turn_metrics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow call turn metrics all" ON call_turn_metrics;
CREATE POLICY "Allow call turn metrics all" ON call_turn_metrics FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


-- ── STORAGE BUCKETS ──────────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public) VALUES ('call-recordings', 'call-recordings', true) ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public read recordings" ON storage.objects;
CREATE POLICY "Public read recordings" ON storage.objects FOR SELECT USING (bucket_id = 'call-recordings');
DROP POLICY IF EXISTS "Service role write recordings" ON storage.objects;
CREATE POLICY "Service role write recordings" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'call-recordings');
